driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always

transport:
  name: "ssh"

platforms:
  - name: centos-6.9
  - name: centos-7.4
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9

#
# Suites
#

suites:
  - name: default-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugin_management]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["ubuntu-18.04", "ubuntu-16.04", "debian-9"]

  - name: system-limits-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugin_management]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["ubuntu-18.04", "ubuntu-16.04", "debian-9"]

  - name: 36x-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.8.20-1"
      rabbitmq:
        version: "3.6.16"
    verifier:
      inspec_tests:
        - test/smoke/36x
    includes: ["ubuntu-16.04"]

  - name: 366-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:19.3.6.13-1"
      rabbitmq:
        version: "3.6.6"
    verifier:
      inspec_tests:
        - test/smoke/36x
    includes: ["ubuntu-16.04"]

  - name: default-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugin_management]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["centos-7.4", "centos-6.9"]

  - name: system-limits-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugin_management]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["centos-7.4"]

  - name: lwrps
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::lwrps]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/lwrps
    includes: ["ubuntu-18.04"]

  - name: cluster-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    includes: ["ubuntu-18.04", "debian-9"]

  - name: cluster-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    includes: ["centos-7.4"]

  - name: default-force-yes
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2-1"
      rabbitmq:
        version: "3.7.12"
    attributes:
      apt:
        confd:
          assume_yes: true
          force-yes: true
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["debian-9"]

  - name: default-force-yes-false
    run_list:
      - recipe[apt]
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      apt:
        confd:
          assume_yes: false
          force-yes: false
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/smoke/default
    includes: ["debian-9"]
