driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6.9
  - name: centos-7.4
  - name: ubuntu-16.04
  - name: debian-9

suites:
  - name: default-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.2.2"
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4"]

  - name: default-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "20.2.2-1"
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["ubuntu-16.04", "debian-9"]

  - name: lwrps
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::lwrps]
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/lwrps
    excludes: ["centos-6.9", "debian-9", "centos-7.4"]

  - name: cluster-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.2.2"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    excludes: ["centos-6.9", "centos-7.4"]

  - name: cluster-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "20.2.2-1"
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/cluster
    excludes: ["ubuntu-16.04", "debian-9"]

  - name: default-force-yes
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.2.2"
    attributes:
      apt:
        confd:
          assume_yes: true
          force-yes: true
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4", "debian-9"]

  - name: default-force-yes-false
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      apt:
        confd:
          assume_yes: false
          force-yes: false
    verifier:
      inspec_tests:
        - test/smoke/default
    excludes: ["centos-6.9", "centos-7.4", "debian-9"]
