driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always

transport:
  name: "ssh"

platforms:
  - name: centos-7.4
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9
  - name: fedora-29
  - name: centos-6.9

#
# Suites
#

suites:
  - name: default-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.12"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["ubuntu-18.04", "ubuntu-16.04", "debian-9"]

  - name: management-plugin-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::mgmt_console]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/management_plugin
    includes: ["ubuntu-18.04"]

  - name: system-limits-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.12"
        systemd:
          limits:
            NOFILE: 54000
    verifier:
      inspec_tests:
        - test/integration/limits
    includes: ["ubuntu-18.04", "ubuntu-16.04", "debian-9"]

  - name: default-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["centos-7.4", "centos-6.9"]

  - name: system-limits-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2-1"
      rabbitmq:
        version: "3.7.13"
        systemd:
          limits:
            NOFILE: 54000
    verifier:
      inspec_tests:
        - test/integration/limits
    includes: ["centos-7.4"]

  - name: lwrps
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::lwrps]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/lwrps
    includes: ["ubuntu-18.04"]

  - name: cluster-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cluster
    includes: ["ubuntu-18.04", "debian-9"]

  - name: cluster-rpm
    run_list:
      - recipe[erlang::esl]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cluster
    includes: ["centos-7.4"]

  - name: default-force-yes
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    attributes:
      apt:
        confd:
          assume_yes: true
          force-yes: true
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["debian-9"]

  - name: default-force-yes-false
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      apt:
        confd:
          assume_yes: false
          force-yes: false
      erlang:
        install_method: "esl"
        esl:
          version: "1:21.2.6-1"
      rabbitmq:
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["debian-9"]

  #
  # Team RabbitMQ Erlang packages
  #

  # Latest Erlang package, Debian, HiPE enabled
  - name: rabbitmq-erlang-latest-deb
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      # relies on node.rabbitmq.erlang.version default
      # which is nil/"install latest"
      rabbitmq:
        erlang:
          enabled: true
          hipe: true
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_deb
    includes: ["debian-9", "ubuntu-18.04"]

  # Erlang package, Debian, version pinning
  - name: rabbitmq-erlang-pinned-deb
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "1:21.2.5-1"
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/pinned_deb
    includes: ["ubuntu-18.04"]

  # Latest Erlang package, RPM
  - name: rabbitmq-erlang-latest-rpm-el7
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      # relies on node.rabbitmq.erlang.version default
      # which is nil/"install latest"
      rabbitmq:
        erlang:
          enabled: true
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_rpm
    includes: ["fedora-29", "centos-7.4"]

  # Erlang package, RPM, version pinning
  - name: rabbitmq-erlang-pinned-rpm-el7
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "21.2.5"
          yum:
            baseurl: https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/7
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/pinned_rpm
    includes: ["fedora-29", "centos-7.4"]

  # Latest Erlang package, RPM, CentOS 6 repo
  - name: rabbitmq-erlang-latest-rpm-el6
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          yum:
            baseurl: https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/6
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_rpm
    includes: ["centos-6.9"]

  # Erlang package, RPM, version pinning, CentOS 6 repo
  - name: rabbitmq-erlang-pinned-rpm-el6
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "21.2.5"
          yum:
            baseurl: https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/6
        version: "3.7.13"
    verifier:
      inspec_tests:
        - test/erlang_package/pinned_rpm
    includes: ["centos-6.9"]
