AlignParameters:
  Enabled: false

AsciiComments:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

MethodLength:
  Max: 18

Naming/FileName:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Style/IfUnlessModifier:
  Enabled: false
